version: "3.7"
services:
    postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=discord_bot
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
        ports:
            - "5432:5432"